name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: wagtail_factories
          POSTGRES_DB: wagtail_factories
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python: ['3.7', '3.8', '3.9']
        django: ['3.2', '4.0']
        wagtail: ['2.15', '2.16']
        include:
          - python: '3.10'
            django: '4.0'
            wagtail: '2.16'
        exclude:
          - wagtail: '2.15'
            django: '4.0'

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      env:
        TEST_DB_NAME: wagtail_factories
        TEST_DB_USER: wagtail_factories
        TEST_DB_PASSWORD: secret
        TOX_ENV: "pytho${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}"
      run: |
        tox -e $TOX_ENV
